### ISSUE TITLE
Typo: "Caracteristics and Orbit"

### ISSUE THREAD

**Issue by WazWaz** [JPLRepo/ResearchBodies#17]

**Comment by JPLRepo** [comment]
Um, "Characteritics" - but anyway. No description. So I guess I close this one.

**Comment by WazWaz** [comment]
It's a typo in the code (and hence in the UI):

researchData_caracteristics = Research data : Caracteristics and Orbit

As you said, it should be "Characteritics and Orbit".

**Comment by JPLRepo** [comment]
ah ok, thanks for the description.

**Comment by JPLRepo** [comment]
fixed, ready for testing.
