### ISSUE TITLE
Oservatory issue

### ISSUE THREAD

**Issue by PetorKukushkin** [JPLRepo/ResearchBodies#26]
I improved the observatory in one saving game. In another preservation of the game, I found that the observatory is also improved to level 2.
Also, I can not take the contract "Research  a Celestial Body" by the fact that the observatory should be level 1.
If this is important: I'm using this mod along with the Galileo planet pack.

**Comment by JPLRepo** [comment]
What version? Are you using the latest? V1.9.5?

**Comment by PetorKukushkin** [comment]
I do not remember. The latter at the time.

**Comment by JPLRepo** [comment]
I tested two separate games - upgraded one game to Observatory level 2.
Loaded second game (without restarted KSP) and it correctly shows Observatory level 1.
Unable to reproduce and no further information supplied.
Closing.
