### ISSUE TITLE
Slow loading after installing this mod

### ISSUE THREAD

**Issue by AlexALX** [JPLRepo/ResearchBodies#30]
Hello, after i installed this mod loading scenes is much slower (in ~3-5 times), for example when i'm launching vessel or open tracking center (loading screen). Does this normal or something wrong? Can i speedup loading times somehow? If i remove this mod everything back to normal. Its makes me choose to use game without mod because waiting for 20-30 seconds for launch vessel is abnormal when without this mod it do it for 5 seconds.

**Comment by AlexALX** [comment]
Here is my output_log.txt if it can help... Also here is my mod list:
000_TRR_Config
AntennaHelper
ContractConfigurator
ContractPacks
DarkMultiPlayer
DistantObject
EnvironmentalVisualEnhancements
FinalFrontier.dat
JSI
KerbalEngineer
Kopernicus
ModularFlightIntegrator
ModuleManager.2.8.1.dll
ModuleManager.ConfigCache
ModuleManager.ConfigSHA
ModuleManager.Physics
ModuleManager.TechTree
Nereid
PlanetShine
PreciseNode
RealPlume
RealPlume-Stock
REPOSoftTech
SCANsat
scatterer
SmokeScreen
Squad
StockVisualEnhancements
SVT
Syncrio
TarsierSpaceTech
TextureReplacerReplaced
Trajectories
TriggerTech
WindowShine

[output_log.txt](https://github.com/JPLRepo/ResearchBodies/files/1556446/output_log.txt)

**Comment by JPLRepo** [comment]
Yup. It is simply the way the mod works.. which is constrained by the way KSP works and loads. And is further exacerbated by the visual enhancement mods you have installed such as scatterer and EVE. There is not a lot I can do about that sorry.
