### ISSUE TITLE
Fixed discover order?

### ISSUE THREAD

**Issue by gyf1214** [JPLRepo/ResearchBodies#34]
I'm testing this mod for my next career play through based on GPP(Galileo's Planet Pack)

It seems that the first planet discovered is always Icarus, the first planet in the system.

I check the code, finding that on completion of "Search the Sky" contracts (@CCContractExtensions.cs:372), it just iterates the undiscovered bodies within the range and picks the first one in the list. I also check the implementation of Database.instance.BodyList (@Database.cs:143), it just loads the list from global.

Is it intended or just a basic version?

Yet it is true that based on the relative position of planets, bodies within the range varied through time. But I still recommend some mechanism other than simply by the index of body in the list. #28 seems a bit complicated. Just a randomization will make it better.

**Comment by JPLRepo** [comment]
Yup. Have randomized it.
