### ISSUE TITLE
API wrapper license (some confusion)

### ISSUE THREAD

**Issue by Rodhern** [JPLRepo/ResearchBodies#35]
I downloaded this MIT licensed file: [RBWrapper.cs](https://github.com/JPLRepo/ResearchBodies/blob/master/API/RBWrapper.cs).

So far so good. Now to the somewhat confusing part. It is mentioned in the [readme](https://github.com/JPLRepo/ResearchBodies/blob/master/README.md) that some parts of this repository are 'all rights reserved' and require express written permission for modification and redistribution. Then there is a reference to license files in the 'Distribution Folder'. So is that e.g. the file tugged away here: [/Distribution/GameData/REPOSoftTech/ResearchBodies/LICENSE&nbsp;Software.txt](https://github.com/JPLRepo/ResearchBodies/blob/master/Distribution/GameData/REPOSoftTech/ResearchBodies/LICENSE%20Software.txt). If it is, it basically says to read the comment in the top of the file. Fair enough, at the end of the day you are offering the mentioned wrapper to the world under an MIT license (which happens to be one of my favourite licenses).

Then when I go to the [wiki](https://github.com/JPLRepo/ResearchBodies/wiki/ResearchBodies-Reflection-wrapper-API) I see this quote
> This reflection wrapper API is used to interface to ResearchBodies.
Before you re-distribute or wish to integrate to this DLL please drop me a PM on the KSP forums, Thanks!
You can find the Wrapper Class here:-
https://github.com/JPLRepo/ResearchBodies/blob/Dev/API/RBWrapper.cs

So, would you prefer to be told when someone considers using/modifying/redistributing the wrapper? My guess is that most people probably are happy to tell you. Right now, I think it just a bit confusing, if that is your preference or not.

**Comment by JPLRepo** [comment]
The RBWrapper is MIT. as per the file.
The parts of the code that are ARR are commented as such.
The wiki quote is simply that I would like people to let me know if they want to integrate into the mod - so if I make changes in the future - I can let them know.

**Comment by Rodhern** [comment]
That makes sense. Thanks.
