### ISSUE TITLE
Part explosions when using with Kopernicus

### ISSUE THREAD

**Issue by seanth** [JPLRepo/ResearchBodies#37]
Craft parts explode when used with Kopernicus. Sometimes the heat explosions happen when zooming out in map view. Other times parts explode due to heat when changing where the craft is controlled from.

Logs at https://www.dropbox.com/sh/qn25y5bnkgs63xq/AADI1G_i8iNa0jD2MAiBdfwZa?dl=0

Video showing an example at https://youtu.be/VRLnmuM9F5o?t=1m24s

I will cross post a this bug with the Kopernicus repo as well. Logs make me think it has something to do with sunlight switching.

**Comment by JPLRepo** [comment]
Logs no longer available.

**Comment by JPLRepo** [comment]
No info for over a year and a half. closing.
