### ISSUE TITLE
ResearchBodies Telescope GUI blank/empty, until Observatory is visited at least once

### ISSUE THREAD

**Issue by SlipstreamZA** [JPLRepo/ResearchBodies#39]
When flying an existing ship in orbit with a ResearchBodies Telescope, the part GUI does not load and is blank/empty, as seen in the image 1 below.

If the Observatory is visited at least once, going back to the same ship the part GUI displays as expected in images 2 and 3

KSP.log file attached [KSP.log](https://github.com/JPLRepo/ResearchBodies/files/2706424/KSP.log) with sequence as follows:
main menu
space center
tracking station
fly ship and researchbodies GUI empty
space center
observatory
tracking station
fly ship researchbodies GUI working as expected

![researchbodies1](https://user-images.githubusercontent.com/44320696/50388485-a62fa900-0720-11e9-8b60-f97610f425ce.jpg)
![researchbodies2](https://user-images.githubusercontent.com/44320696/50388495-06264f80-0721-11e9-9f97-bedb14ecacb4.jpg)
![researchbodies3](https://user-images.githubusercontent.com/44320696/50388498-0c1c3080-0721-11e9-95f8-83f446b39ac6.jpg)

**Comment by SlipstreamZA** [comment]
PR submitted, GUI wasn't displaying due to texture not being loaded, visiting the Observatory loaded needed textures. Moved already loaded checks and error printouts to central texture loading code

**Comment by JPLRepo** [comment]
V1.9.9 fixes this issue.
