### ISSUE TITLE
Vessels with Telescope active freezes Game

### ISSUE THREAD

**Issue by marcoboy123** [JPLRepo/ResearchBodies#42]
Edit: Probably TST Issue, would be cool if you move this over, or tell me if i should make a new post on your TST github

So yeah. I have this modded Career going on. I tried to play around for literally about 2 hours now , to find the culprit. Its this mod.
my game freezes in my Mainscreen menu of my Career (The screen where every building) is , randomly. For about 15 Seconds to 1 Minute. That happens very often in intervals between 10 seconds. it doesnt freeze in Flymode, even on Timewarp. Just in the mainscreen of my savegame.
I launched 2 Telescopes for Contracts.Contracts.(One of which is the Astroid Sentinel thing from this mod, the other is from TST) After testing i found out:
Deactivating the telescopes didnt do anything. Deleting the vessels with the Telescope / Asteroid Sentinel does the trick tho. No more lag without these vessels. (I didnt find out tho which of these, the Asteroid Scanner or the normal Space Telescope) And im unsure myself if it has anything todo with the contracts. But its certain its one of those vessels with the Telescopes onboard that let my game freeze.

ignore the whole errorspam in Output.log of Resource System Error: Requested resource (id: 313203211) does not exist ,that occured through an Kerbalism update.

https://www.mediafire.com/file/3p3yajeatxuw8oi/output_log.txt/file
https://www.mediafire.com/file/ncwlgutdxtgj7tp/ResearchBodies.log/file

Thank you, and i hope we will somehow solve this issue ^^

**Comment by JPLRepo** [comment]
Seems related to either scatterer or Eve mods...
try uninstalling these and see which one is causing the problem.

**Comment by JPLRepo** [comment]
No info for a year. Closing.
