### ISSUE TITLE
it has already researched all?

### ISSUE THREAD

**Issue by WeasselDW** [JPLRepo/ResearchBodies#45]
i wanted to play the mod but it saids i already have it researched
a log i found:
`
ResearchBodies1.9.9.0
Loaded up on 12-03-2019 17:39:25 PM.

17:44:38 PM [LOG] 3/12/2019 5:44:38 PM,ResearchBodies,Observatory Awake - Construction Begins
17:44:41 PM [LOG] 3/12/2019 5:44:41 PM,ResearchBodies,Observatory Construction - Post Psystem Spawn Point Begins
17:44:42 PM [LOG] 3/12/2019 5:44:42 PM,ResearchBodies,Observatory Construction - Post Psystem Spawn Point Ends
17:44:42 PM [KSP] ==== Scene Switch to MAINMENU ! ====
17:44:44 PM [LOG] 3/12/2019 5:44:44 PM,ResearchBodies,Awake
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,LoadDatabase
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Loading Priority database
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Loading ignore body list from database
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Body Ignore Data for Sun : True True True True
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Body Ignore Data for Kerbin : True True True True
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Body Ignore Data for Mun : True True True True
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Body Ignore Data for Minmus : True True True False
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Body Ignore Data for Duna : True True False False
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Body Ignore Data for Eve : True True False False
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Body Ignore Data for Jool : True True False False
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Body Ignore Data for Laythe : True False False False
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Body Ignore Data for Vall : True False False False
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Body Ignore Data for Tylo : True False False False
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Loading mods databases
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Chances to get a body is set to 0
17:44:45 PM [LOG] 3/12/2019 5:44:45 PM,ResearchBodies,Loaded gamemode-related information : enable mod in sandbox = False, allow tracking with Tracking station lvl 1 = False
17:45:04 PM [KSP] ==== Scene Switch to SPACECENTER ! ====
17:45:15 PM [LOG] 3/12/2019 5:45:15 PM,ResearchBodies,ResearchBodies Constructor
17:45:15 PM [LOG] 3/12/2019 5:45:15 PM,ResearchBodies,OnAwake in SPACECENTER
17:45:15 PM [LOG] 3/12/2019 5:45:15 PM,ResearchBodies,Adding SpaceCenterManager
17:45:15 PM [LOG] 3/12/2019 5:45:15 PM,ResearchBodies,onGameStatePostLoad
17:45:15 PM [LOG] 3/12/2019 5:45:15 PM,ResearchBodies,Database ApplySettings
17:45:15 PM [LOG] 3/12/2019 5:45:15 PM,ResearchBodies,onGameStatePostLoad
17:45:15 PM [LOG] 3/12/2019 5:45:15 PM,ResearchBodies,Database ApplySettings
17:45:15 PM [LOG] 3/12/2019 5:45:15 PM,ResearchBodies,RBGameSettings Loading Complete
17:45:15 PM [LOG] 3/12/2019 5:45:15 PM,ResearchBodies,ResearchBodies Scenario Onload Completed.
17:45:15 PM [LOG] 3/12/2019 5:45:15 PM,ResearchBodies,Observatory SpaceCenter Scene Loading...
17:45:15 PM [LOG] 3/12/2019 5:45:15 PM,ResearchBodies,Scene SpaceCenter
17:45:16 PM [LOG] 3/12/2019 5:45:16 PM,ResearchBodies,Observatory SpaceCenter Scene Loading Completed.
17:45:17 PM [LOG] 3/12/2019 5:45:17 PM,ResearchBodies,RBGameSettings Saving Complete
17:45:17 PM [LOG] 3/12/2019 5:45:17 PM,ResearchBodies,ResearchBodies Scenario OnSave completed.
17:45:24 PM [LOG] 3/12/2019 5:45:24 PM,ResearchBodies,RBGameSettings Saving Complete
17:45:24 PM [LOG] 3/12/2019 5:45:24 PM,ResearchBodies,ResearchBodies Scenario OnSave completed.
17:45:24 PM [LOG] 3/12/2019 5:45:24 PM,ResearchBodies,Game scene load requested: TRACKSTATION
17:45:24 PM [LOG] 3/12/2019 5:45:24 PM,ResearchBodies,OnDestroy
17:45:24 PM [LOG] 3/12/2019 5:45:24 PM,ResearchBodies,ResearchBodies Child Destroy for ScenarioLogic
17:45:24 PM [KSP] ==== Scene Switch to TRACKSTATION ! ====
17:45:26 PM [LOG] 3/12/2019 5:45:26 PM,ResearchBodies,ResearchBodies Constructor
17:45:26 PM [LOG] 3/12/2019 5:45:26 PM,ResearchBodies,OnAwake in TRACKSTATION
17:45:26 PM [LOG] 3/12/2019 5:45:26 PM,ResearchBodies,Adding TrackingStationController
17:45:26 PM [LOG] 3/12/2019 5:45:26 PM,ResearchBodies,onGameStatePostLoad
17:45:26 PM [LOG] 3/12/2019 5:45:26 PM,ResearchBodies,Database ApplySettings
17:45:26 PM [LOG] 3/12/2019 5:45:26 PM,ResearchBodies,RBGameSettings Loading Complete
17:45:26 PM [LOG] 3/12/2019 5:45:26 PM,ResearchBodies,ResearchBodies Scenario Onload Completed.
17:45:42 PM [LOG] 3/12/2019 5:45:42 PM,ResearchBodies,RBGameSettings Saving Complete
17:45:42 PM [LOG] 3/12/2019 5:45:42 PM,ResearchBodies,ResearchBodies Scenario OnSave completed.
17:45:55 PM [LOG] 3/12/2019 5:45:55 PM,ResearchBodies,RBGameSettings Saving Complete
17:45:55 PM [LOG] 3/12/2019 5:45:55 PM,ResearchBodies,ResearchBodies Scenario OnSave completed.
17:45:56 PM [LOG] 3/12/2019 5:45:56 PM,ResearchBodies,Game scene load requested: SPACECENTER
17:45:56 PM [LOG] 3/12/2019 5:45:56 PM,ResearchBodies,OnDestroy
17:45:56 PM [LOG] 3/12/2019 5:45:56 PM,ResearchBodies,ResearchBodies Child Destroy for ScenarioLogic
17:45:56 PM [KSP] ==== Scene Switch to SPACECENTER ! ====
17:46:07 PM [LOG] 3/12/2019 5:46:07 PM,ResearchBodies,ResearchBodies Constructor
17:46:07 PM [LOG] 3/12/2019 5:46:07 PM,ResearchBodies,OnAwake in SPACECENTER
17:46:07 PM [LOG] 3/12/2019 5:46:07 PM,ResearchBodies,Adding SpaceCenterManager
17:46:07 PM [LOG] 3/12/2019 5:46:07 PM,ResearchBodies,onGameStatePostLoad
17:46:07 PM [LOG] 3/12/2019 5:46:07 PM,ResearchBodies,Database ApplySettings
17:46:07 PM [LOG] 3/12/2019 5:46:07 PM,ResearchBodies,RBGameSettings Loading Complete
17:46:07 PM [LOG] 3/12/2019 5:46:07 PM,ResearchBodies,ResearchBodies Scenario Onload Completed.
17:46:09 PM [LOG] 3/12/2019 5:46:09 PM,ResearchBodies,Observatory SpaceCenter Scene Loading...
17:46:09 PM [LOG] 3/12/2019 5:46:09 PM,ResearchBodies,Scene SpaceCenter
17:46:09 PM [LOG] 3/12/2019 5:46:09 PM,ResearchBodies,Observatory SpaceCenter Scene Loading Completed.
17:46:13 PM [LOG] 3/12/2019 5:46:13 PM,ResearchBodies,RBGameSettings Saving Complete
17:46:13 PM [LOG] 3/12/2019 5:46:13 PM,ResearchBodies,ResearchBodies Scenario OnSave completed.
17:46:14 PM [LOG] 3/12/2019 5:46:14 PM,ResearchBodies,Game scene load requested: MAINMENU
17:46:14 PM [LOG] 3/12/2019 5:46:14 PM,ResearchBodies,OnDestroy
17:46:14 PM [LOG] 3/12/2019 5:46:14 PM,ResearchBodies,ResearchBodies Child Destroy for ScenarioLogic
17:46:14 PM [KSP] ==== Scene Switch to MAINMENU ! ====
17:46:45 PM [LOG] 3/12/2019 5:46:45 PM,ResearchBodies,OnDestroy
`

**Comment by JPLRepo** [comment]
I don't understand your question. there are no errors in the log provided.
