### ISSUE TITLE
ResearchBodiesMMRemoteTech.cfg breaks other mods

### ISSUE THREAD

**Issue by SirMortimer** [JPLRepo/ResearchBodies#48]
I assume the file is not supposed to be in the distributed zip any more.

Anyways, Kerbalism users noticed a massive drain of EC with just a single Mk1 pod on the launch pad (12 ec/s), no additional parts, draining the battery within seconds. They didn't have RT installed. Due to some ModuleManager wizardry that is above my pay grade, ResearchBodiesMMRemoteTech.cfg seems to affect the EC usage of the internal ModuleDataTransmitter in the Mk1 pod.

If the file should be in the distribution and currently is missing in the git repository, please consider replacing `FOR[RemoteTech]` with `NEEDS[RemoteTech]`.

**Comment by gotmachine** [comment]
Can confirm. The `FOR[RemoteTech]` is causing all other mods using the proper `NEEDS[RemoteTech]` in a patch to have that patch wrongly applied. 
BEFORE/FOR/AFTER is registering the NEEDS keywords.

**Comment by SirMortimer** [comment]
For clarification, this is the content of that file:

```
@PART[TrackBodiesTelescope]:FOR[RemoteTech]
{
	%MODULE[ModuleSPU] {
	}
	
	%MODULE[ModuleRTAntennaPassive]	{
		%TechRequired = unmannedTech
		%OmniRange = 3000
		
		%TRANSMITTER {
			%PacketInterval = 0.3
			%PacketSize = 2
			%PacketResourceCost = 15.0
		}
	}
}
```

`FOR[RemoteTech]`really is a problem here. What this apparently does is declare the `RemoteTech` key that is checked in the `NEEDS[RemoteTech]` in all patch files. It essentially enables RemoteTech configs for all mods that have any.

This needs to be fixed ASAP.

**Comment by JPLRepo** [comment]
Will be fixed in next version released once KSP 1.9 is released.

**Comment by SirMortimer** [comment]
Any chance this could be expedited? We currently have a warning in Kerbalism when ResearchBodies is installed, and are going to release a new version soon. I'd like to remove that warning.

**Comment by JPLRepo** [comment]
this was fixed already.
