### ISSUE TITLE
ResearchBodies breaks Outer Planet Mod

### ISSUE THREAD

**Issue by NicholasZidel** [JPLRepo/ResearchBodies#49]
When ResearchBodies is installed OPM only adds one planet which adjusts the orbit of Eeloo, but does not add the other planets or moons from the mod. By uninstalling ResearchBodies OPM works as intended.

**Comment by JPLRepo** [comment]
Sounds like an OPM issue. don't see how this mod impacts another mod from doing what it should. No Logs provided either.

**Comment by JPLRepo** [comment]
See https://github.com/JPLRepo/ResearchBodies/issues/50
