### ISSUE TITLE
VesselInSOIInfo.cs is missing from Repository

### ISSUE THREAD

**Issue by Symondus** [JPLRepo/ResearchBodies#55]
Hi 
I wanted to debug a problem i have with the interaction between the Beyond Home Kopernicus pack and Research Bodies (similar to  Ticket #50 - where it seems that the ignore tags on the Planets get reset to true instead of staying on false.

Here i noticed that the file 
    <Compile Include="VesselInSOIInfo.cs" />
is missing from the GitRepository. I could not find it on older versions of the mod, either.

It would be great if you could add that, so that i can work on a solution for that other problem.

Thanks a lot

**Comment by Symondus** [comment]
I removed all the code relating to said file and rebuilt the library. Now all bodies are hidden as expected. 

But, the research level of two moons that i visited with a probe were only set to 30%, so i could not yet see their orbits. I am not sure if that is intended as the mod states that research should be instantly set to 100% when you happen to meet a planet. The orbits were visible right after i reached those moons but are gone now after reloading the file (this could of course also be related to the deletion of the VesselInSOIInfo-referring code.

**Comment by JPLRepo** [comment]
yes. the vesselinsoi is about vessels going into the soi of a CB. they are no longer set to 100% straight away. but are over time if the vessel remains in the SOI. 
As for the missing file I will follow up.

**Comment by JPLRepo** [comment]
Added the mission source file to dev branch.
