### ISSUE TITLE
A feature request

### ISSUE THREAD

**Issue by CptKermit** [JPLRepo/ResearchBodies#56]
One small thing that does bother me a bit is so small I think it goes largely unnoticed so it's probably not worth the effort to implement but here goes;

When a body is discovered its' name is given in the description. The name then appears in the Research Bodies list in telescopes and the ground base yet in the tracking station it is an unknown object. I've played before so I know how to connect the dots without thinking of it but what about a new player who didn't pay close attention to the name in the description or has so many unknowns that they have lost track and the Take a Picture contracts start coming up? 
I know it's not that hard to figure out, there are no repercussions for taking pix of the wrong planet, I don't think it has ever been mentioned before, but it seems odd to me that one out of three name labels says unknown. 
I can understand if it's an attempt to add to the discovery emersion but objects are always named as soon as it is agreed that it is indeed a new object. An "unknown object" really doesn't fit in this context. You'll never find one on a star map. 

Just a thought.

Oh! and I'd also like to see worms on Arrakis. I mean Duna. LOL

Thanks again. I seriously can't play career mode without this mod.

**Comment by JPLRepo** [comment]
Unfortunately. the discovery level. and what the name of the object is in the tracking station is not something I can change as that's part of the stock KSP code base.
