### ISSUE TITLE
Research bodies mod not working

### ISSUE THREAD

**Issue by PlaneteniumTheory** [JPLRepo/ResearchBodies#57]
I started using Research bodies and made a new save ,on my modded ksp.After that when I started launching my rockets,I checked the Tracking Station and all the planets were loaded.I wanted to go into the observatory ,but since it could only be opened at level 2 of the Tracking station,i gave myself some funds and upgraded the Tracking station.Then I entered the observatory and the game was stuck. I tried creating a new sandbox save with Research bodies,and the first thing i did in that was go in the Tracking station.There only the Sun could be seen which was good,but i want to use the plugin for the older save that i have.Is it possible?
btw,I am using KsRss,and i don't know where the log file is which you ask for is.
![Screenshot (1899)](https://user-images.githubusercontent.com/76861138/120266212-13b36c80-c2bf-11eb-9549-df27d630a47c.png)

**Comment by PlaneteniumTheory** [comment]
I have clicked the observatory in the above pic and the game ust stopped,you can hear the observatory music ,while i can zoom in and out on the space centre

**Comment by PlaneteniumTheory** [comment]
[Player.log](https://github.com/JPLRepo/ResearchBodies/files/6573584/Player.log)

**Comment by PlaneteniumTheory** [comment]
I also saw that if you create a save with research bodies working,you need to go to the tracking station everytime you start the game otherwise it will show all bodies are discovered and it can't revert it then

**Comment by JPLRepo** [comment]
You are running this mod in an unsupported version of KSP.
