### ISSUE TITLE
Reverting to an older save game doesn't revert the discovered bodies

### ISSUE THREAD

**Issue by rasta013** [JPLRepo/ResearchBodies#6]
The researchbodies.cfg in the save folder doesn't get reset in the event of a save game reload or reverted flight after doing an initial discovery.  Any discovered bodies remain and can be researched but the science gained for discovery is lost after reload or reverting a flight.

**Comment by JPLRepo** [comment]
The whole load/save system within this Mod needs to be re-written.
It also does not persist any settings that the user may set.

**Comment by JPLRepo** [comment]
Should be fixed by the new persistence into the persistent.sfs file in V1.8
